<?php
/**
 * @file ip_blocking.module
 */

/**
 * Implements hook_config_info().
 */
function ip_blocking_config_info() {
  $prefixes['ip_blocking.settings'] = array(
    'label' => t('IP address blocking'),
    'group' => t('Configuration'),
  );
  
  return $prefixes;
}

/**
 * Implements hook_permission().
 *
 */
function ip_blocking_permission() {
  return array(
    'block IP addresses' => array(
      'title' => t('Administer IP address blocking')
    ),
  );
}

/**
 * Implements hook_menu().
 *
 */
function ip_blocking_menu() {
  $items = array();

  $items['admin/config/people/ip-blocking'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'IP address blocking',
    'description' => 'Manage blocked IP addresses.',
    'page callback' => 'ip_blocking',
    'access arguments' => array('block IP addresses'),
    'file' => 'ip_blocking.admin.inc',
  );
  
  $items['admin/config/people/ip-blocking/main'] = array(
    'title' => 'Main',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  
  $items['admin/config/people/ip-blocking/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('ip_blocking_settings_form'),
    'file' => 'ip_blocking.admin.inc',
    'access arguments' => array('block IP addresses'),
    'weight' => 2,
  );
  
  
  $items['admin/config/people/ip-blocking/unblock/%blocked_ip'] = array(
    'title' => 'Unblock IP address',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('ip_blocking_unblock', 5),
    'access arguments' => array('block IP addresses'),
    'file' => 'ip_blocking.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_boot().
 *
 */
function ip_blocking_boot() {

  $ip = check_plain(ip_address());
  
  // Deny access to blocked IP address.
  if (ip_is_denied($ip)) {
    $config      = config('ip_blocking.settings');
    $log_enabled = $config->get('log_enabled');
    $return_404  = $config->get('return_404');
    $request     = htmlspecialchars($_SERVER['REQUEST_URI']);
    $ua_string   = isset($_SERVER['HTTP_USER_AGENT']) ? htmlspecialchars($_SERVER['HTTP_USER_AGENT']) : '';
    
    if($return_404) {
      header($_SERVER['SERVER_PROTOCOL'] . ' 404  Not Found');
    }
    else {
      header($_SERVER['SERVER_PROTOCOL'] . ' 403 Forbidden');
      print 'Sorry, IP address ' . $ip . ' has been banned.';
    }
    
    if($log_enabled) {
      blocked_ip_log($ip, $request, $ua_string);
    }

    exit();
  }
}

/**
 * Checks to see if an IP address has been blocked.
 *
 * Blocked IP addresses are stored in the database only.
 * @param $ip IP address to check.
 *
 * @return bool TRUE if access is denied, FALSE if access is allowed.
 */
function ip_is_denied($ip) {
  $denied = FALSE;
  
  if (class_exists('Database', FALSE)) {
    $denied = (bool)db_query("SELECT 1 FROM {blocked_ips} WHERE ip = :ip", array(':ip' => $ip))->fetchField();
  }
  
  return $denied;
}

/**
 * Retrieve a blocked IP address from the database (used on admin page).
 *
 * @param $iid integer The ID of the blocked IP address to retrieve.
 *
 * @return The blocked IP address from the database as an array.
 */
function blocked_ip_load($iid) {
  return db_query("SELECT * FROM {blocked_ips} WHERE iid = :iid", array(':iid' => $iid))->fetchAssoc();
}

/**
 * Log access attempt
 * 
 * @param string $ip
 */
function blocked_ip_log($ip, $request, $ua_string) {
  $watchdog_message = 'Access attempt from blocked IP: ' . $ip . '; request: ' . $request . '; User-Agent: ' . $ua_string;
  watchdog(
    'blocked_ip',
    $watchdog_message,
    NULL,
    WATCHDOG_WARNING
  );
}